_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.16
        t:
            "1":
                - 3
                - 53
                - 55
            "2":
                - 3
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.7.16
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
algo:
    value: trpo_lagrangian
cost_lim:
    value: 25
robot:
    value: Point
save_freq:
    value: 10
seed:
    value: 0
start_epoch:
    value: 230
target_kl:
    value: 0.01
task:
    value: Goal2
total_epochs:
    value: 333
